### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by NullUserException** [BeneficialCode/adb#1]
It looks like this project can be compiled with Visual Studio 2019 basically as is (after retargeting it to v142), even though it says Visual Studio 2022 is a prerequisite.

There are only two caveats:

1. vcpkg fails to compile boringssl, unless you have Windows SDK >= 10.0.22000. Previous versions of the Windows SDK are missing stdalign.h. See a similar issue here:
  ‎ 
  https://github.com/google-deepmind/mujoco/issues/862
  ‎ 
  It seems like this header has been removed from boringssl, so this may no longer be an issue in the future.

2. In ResourceTypes.cpp, `iResTable::add` uses `append_range()` on an `std::vector`, which is a C++23 feature. I fixed it with this workaround:

```
// replace this line (~4260)
typeList.append_range(srcPg->types[j]);

// with this:
#ifdef __cpp_lib_containers_ranges
    typeList.append_range(srcPg->types[j]);
#else
    typeList.insert(typeList.end(), srcPg->types[j].cbegin(), srcPg->types[j].cend());
#endif
```

**Comment by BeneficialCode** [comment]
Thanks. I will fix the second caveat.
